name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -f -p $HOME/miniconda
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda init bash

    - name: Add conda to system path
      run: echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Activate conda environment
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate base

    - name: Install dependencies
      run: |
        conda env update --file .github/workflows/environment.yml --name base

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest

